# Generated by Django 4.1 on 2022-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('id',), 'verbose_name': 'Новый', 'verbose_name_plural': 'Новые'},
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
